name: Build and Release Extension

on:
  push:
    tags:
      - '*'
  pull_request:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0)'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install web-ext
        run: npm install --global web-ext
      - name: Build extension
        run: web-ext build
      - name: Rename artifact
        run: |
          FILE=$(ls web-ext-artifacts/*.zip | head -n 1)
          mv "$FILE" "${FILE%.zip}.xpi"
          echo "ARTIFACT=${FILE%.zip}.xpi" >> "$GITHUB_ENV"
      - name: Set tag name
        if: github.event_name != 'pull_request'
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> "$GITHUB_ENV"
          else
            echo "TAG_NAME=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          fi
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ${{ env.ARTIFACT }}
      - name: Create GitHub release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARTIFACT }}
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
